-- Flyway Migration Script
-- Version: V1__Create_Loan_Tables.sql
-- Description: Creates loan tables with 200 columns and inserts 100 rows of dummy data

-- Create main loan table with 200 columns
CREATE TABLE loan (
    -- Primary identifiers (5 columns)
    loan_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    loan_number VARCHAR(50) UNIQUE NOT NULL,
    application_id VARCHAR(50) UNIQUE,
    external_loan_id VARCHAR(100),
    legacy_loan_id VARCHAR(50),

    -- Borrower information (25 columns)
    borrower_first_name VARCHAR(100),
    borrower_middle_name VARCHAR(100),
    borrower_last_name VARCHAR(100),
    borrower_suffix VARCHAR(10),
    borrower_ssn VARCHAR(20),
    borrower_date_of_birth DATE,
    borrower_email VARCHAR(255),
    borrower_phone VARCHAR(20),
    borrower_mobile VARCHAR(20),
    borrower_work_phone VARCHAR(20),
    borrower_marital_status VARCHAR(20),
    borrower_citizenship VARCHAR(50),
    borrower_residency_status VARCHAR(50),
    borrower_employment_status VARCHAR(50),
    borrower_occupation VARCHAR(100),
    borrower_employer_name VARCHAR(200),
    borrower_employer_phone VARCHAR(20),
    borrower_years_employed DECIMAL(5,2),
    borrower_monthly_income DECIMAL(15,2),
    borrower_annual_income DECIMAL(15,2),
    borrower_other_income DECIMAL(15,2),
    borrower_credit_score INT,
    borrower_education_level VARCHAR(50),
    borrower_dependents INT,
    borrower_housing_status VARCHAR(50),

    -- Co-borrower information (25 columns)
    co_borrower_first_name VARCHAR(100),
    co_borrower_middle_name VARCHAR(100),
    co_borrower_last_name VARCHAR(100),
    co_borrower_suffix VARCHAR(10),
    co_borrower_ssn VARCHAR(20),
    co_borrower_date_of_birth DATE,
    co_borrower_email VARCHAR(255),
    co_borrower_phone VARCHAR(20),
    co_borrower_mobile VARCHAR(20),
    co_borrower_work_phone VARCHAR(20),
    co_borrower_marital_status VARCHAR(20),
    co_borrower_citizenship VARCHAR(50),
    co_borrower_residency_status VARCHAR(50),
    co_borrower_employment_status VARCHAR(50),
    co_borrower_occupation VARCHAR(100),
    co_borrower_employer_name VARCHAR(200),
    co_borrower_employer_phone VARCHAR(20),
    co_borrower_years_employed DECIMAL(5,2),
    co_borrower_monthly_income DECIMAL(15,2),
    co_borrower_annual_income DECIMAL(15,2),
    co_borrower_other_income DECIMAL(15,2),
    co_borrower_credit_score INT,
    co_borrower_education_level VARCHAR(50),
    co_borrower_dependents INT,
    co_borrower_housing_status VARCHAR(50),

    -- Address information (20 columns)
    property_address_line1 VARCHAR(255),
    property_address_line2 VARCHAR(255),
    property_city VARCHAR(100),
    property_state VARCHAR(50),
    property_zip_code VARCHAR(20),
    property_county VARCHAR(100),
    property_country VARCHAR(100),
    mailing_address_line1 VARCHAR(255),
    mailing_address_line2 VARCHAR(255),
    mailing_city VARCHAR(100),
    mailing_state VARCHAR(50),
    mailing_zip_code VARCHAR(20),
    mailing_county VARCHAR(100),
    mailing_country VARCHAR(100),
    previous_address_line1 VARCHAR(255),
    previous_city VARCHAR(100),
    previous_state VARCHAR(50),
    previous_zip_code VARCHAR(20),
    years_at_current_address DECIMAL(5,2),
    months_at_current_address INT,

    -- Loan details (35 columns)
    loan_type VARCHAR(50),
    loan_purpose VARCHAR(100),
    loan_amount DECIMAL(15,2),
    requested_amount DECIMAL(15,2),
    approved_amount DECIMAL(15,2),
    disbursed_amount DECIMAL(15,2),
    outstanding_balance DECIMAL(15,2),
    principal_balance DECIMAL(15,2),
    interest_rate DECIMAL(7,4),
    annual_percentage_rate DECIMAL(7,4),
    loan_term_months INT,
    remaining_term_months INT,
    payment_frequency VARCHAR(20),
    monthly_payment DECIMAL(15,2),
    first_payment_date DATE,
    maturity_date DATE,
    loan_status VARCHAR(50),
    loan_sub_status VARCHAR(50),
    origination_date DATE,
    funding_date DATE,
    application_date DATE,
    approval_date DATE,
    closing_date DATE,
    first_disbursement_date DATE,
    loan_officer_id VARCHAR(50),
    loan_officer_name VARCHAR(200),
    underwriter_id VARCHAR(50),
    underwriter_name VARCHAR(200),
    processor_id VARCHAR(50),
    processor_name VARCHAR(200),
    origination_fee DECIMAL(15,2),
    processing_fee DECIMAL(15,2),
    late_fee_amount DECIMAL(15,2),
    prepayment_penalty DECIMAL(15,2),
    loan_to_value_ratio DECIMAL(7,4),

    -- Property details (20 columns)
    property_type VARCHAR(50),
    property_use VARCHAR(50),
    property_value DECIMAL(15,2),
    appraised_value DECIMAL(15,2),
    purchase_price DECIMAL(15,2),
    property_year_built INT,
    property_square_feet INT,
    property_bedrooms INT,
    property_bathrooms DECIMAL(3,1),
    property_stories INT,
    property_garage_spaces INT,
    property_lot_size DECIMAL(10,2),
    property_condition VARCHAR(50),
    property_zoning VARCHAR(50),
    hoa_fee DECIMAL(10,2),
    property_tax_annual DECIMAL(15,2),
    homeowners_insurance DECIMAL(15,2),
    flood_insurance DECIMAL(15,2),
    pmi_amount DECIMAL(15,2),
    escrow_account_balance DECIMAL(15,2),

    -- Financial details (25 columns)
    down_payment_amount DECIMAL(15,2),
    down_payment_percentage DECIMAL(7,4),
    debt_to_income_ratio DECIMAL(7,4),
    front_end_ratio DECIMAL(7,4),
    back_end_ratio DECIMAL(7,4),
    total_monthly_debt DECIMAL(15,2),
    auto_loan_payment DECIMAL(15,2),
    credit_card_payment DECIMAL(15,2),
    student_loan_payment DECIMAL(15,2),
    other_loan_payment DECIMAL(15,2),
    alimony_payment DECIMAL(15,2),
    child_support_payment DECIMAL(15,2),
    total_assets DECIMAL(15,2),
    liquid_assets DECIMAL(15,2),
    checking_account_balance DECIMAL(15,2),
    savings_account_balance DECIMAL(15,2),
    retirement_account_balance DECIMAL(15,2),
    investment_account_balance DECIMAL(15,2),
    total_liabilities DECIMAL(15,2),
    credit_card_debt DECIMAL(15,2),
    outstanding_judgments DECIMAL(15,2),
    tax_liens DECIMAL(15,2),
    bankruptcy_flag BOOLEAN,
    foreclosure_flag BOOLEAN,
    short_sale_flag BOOLEAN,

    -- Risk and compliance (20 columns)
    risk_rating VARCHAR(20),
    risk_score DECIMAL(7,2),
    fraud_score DECIMAL(7,2),
    compliance_status VARCHAR(50),
    kyc_status VARCHAR(50),
    kyc_verification_date DATE,
    aml_status VARCHAR(50),
    aml_verification_date DATE,
    ofac_status VARCHAR(50),
    ofac_check_date DATE,
    credit_check_date DATE,
    income_verification_status VARCHAR(50),
    employment_verification_status VARCHAR(50),
    asset_verification_status VARCHAR(50),
    appraisal_status VARCHAR(50),
    title_search_status VARCHAR(50),
    insurance_verification_status VARCHAR(50),
    regulatory_product_type VARCHAR(50),
    hoepa_status VARCHAR(50),
    hpml_status VARCHAR(50),

    -- Payment tracking (15 columns)
    last_payment_date DATE,
    last_payment_amount DECIMAL(15,2),
    next_payment_due_date DATE,
    next_payment_amount DECIMAL(15,2),
    total_payments_made INT,
    payments_past_due INT,
    days_past_due INT,
    total_paid_principal DECIMAL(15,2),
    total_paid_interest DECIMAL(15,2),
    total_paid_fees DECIMAL(15,2),
    late_payment_count INT,
    missed_payment_count INT,
    prepayment_amount DECIMAL(15,2),
    payoff_amount DECIMAL(15,2),
    payoff_date DATE,

    -- Audit and tracking (15 columns)
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(100),
    version INT DEFAULT 1,
    record_status VARCHAR(20) DEFAULT 'ACTIVE',
    data_source VARCHAR(100),
    source_system VARCHAR(100),
    migration_batch_id VARCHAR(50),
    last_sync_date TIMESTAMP,
    notes TEXT,
    internal_notes TEXT,
    customer_notes TEXT,
    special_instructions TEXT,
    tags VARCHAR(500)
);

-- Create indexes for better query performance
CREATE INDEX idx_loan_number ON loan(loan_number);
CREATE INDEX idx_borrower_ssn ON loan(borrower_ssn);
CREATE INDEX idx_loan_status ON loan(loan_status);
CREATE INDEX idx_origination_date ON loan(origination_date);
CREATE INDEX idx_application_date ON loan(application_date);
CREATE INDEX idx_loan_officer_id ON loan(loan_officer_id);